title: "Gauteng Wellbeing Mapper"
description: "A mobile app for studying mental wellbeing in environmental & climate context - Part of the Planet4Health project"
baseurl: "/guateng-wellbeing-mapper-app"
url: "https://activityspacelab.github.io"

# GitHub Pages settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
mermaid: true

# Site settings
author: "Planet4Health Project"
email: "john.palmer@upf.edu"
github_username: "ActivitySpaceLab"

# Planet4Health branding
logo_url: "assets/P4H_logo/P4H logo png - transparent/LOGO PLANET4HEALTH-horizontal .png"
project_url: "https://planet4health.eu"
project_name: "Planet4Health"

# Navigation
header_pages:
  - USER_GUIDE.md
  - DEVELOPER_GUIDE.md
  - API_REFERENCE.md
  - PRIVACY.md

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# SEO settings
lang: en
google_analytics: # Add your GA tracking ID if needed

# Social links
social:
  - name: Planet4Health Website
    url: https://planet4health.eu
  - name: GitHub
    url: https://github.com/ActivitySpaceLab/guateng-wellbeing-mapper-app

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
