name: Deploy App Release to GitHub Releases

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

jobs:  
  build:
    runs-on: macos-latest # Use macOS for iOS builds
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.27.1' # Match your fvm version
    
    - name: Get version from tag
      id: version
      run: echo "content=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Get flutter dependencies
      run: flutter pub get
      working-directory: guateng-wellbeing-mapper-app

    - name: Statically analyze the Dart code for any errors
      run: flutter analyze
      working-directory: guateng-wellbeing-mapper-app
    
    - name: Run tests for our flutter project
      run: flutter test
      working-directory: guateng-wellbeing-mapper-app

    # Android Builds
    - name: Build Android APK (Release)
      run: flutter build apk --release --split-per-abi
      working-directory: guateng-wellbeing-mapper-app

    - name: Build Android App Bundle (Release)
      run: flutter build appbundle --release
      working-directory: guateng-wellbeing-mapper-app

    # iOS Builds
    - name: Install iOS dependencies
      run: cd ios && pod install && cd ..
      working-directory: guateng-wellbeing-mapper-app
      
    - name: Build iOS (Release)
      run: flutter build ios --release --no-codesign
      working-directory: guateng-wellbeing-mapper-app
    
    - name: Create a Release in GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          guateng-wellbeing-mapper-app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          guateng-wellbeing-mapper-app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          guateng-wellbeing-mapper-app/build/app/outputs/flutter-apk/app-x86_64-release.apk
          guateng-wellbeing-mapper-app/build/app/outputs/bundle/release/app-release.aab
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.version.outputs.content }}
        name: "Wellbeing Mapper ${{ steps.version.outputs.content }}"
        body: |
          ## Wellbeing Mapper Release ${{ steps.version.outputs.content }}
          
          ### 📱 Downloads
          - **Android App Bundle (Recommended)**: `app-release.aab` - Upload to Google Play Console
          - **Android APKs**: Individual APK files for direct installation
          - **iOS Build**: Requires archiving in Xcode for App Store Connect
          
          ### 🔧 What's Included
          - ✅ Android release builds (APK + AAB)
          - ✅ iOS release build (requires Xcode archiving for distribution)
          - ✅ Fully tested and analyzed code
          
          ### 📋 Next Steps
          1. **Android**: Upload `app-release.aab` to Google Play Console
          2. **iOS**: Archive the built app in Xcode and upload to App Store Connect
        draft: false
        prerelease: false