name: Deploy App Release to GitHub Releases

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

jobs:  
  build:
    runs-on: macos-latest # Use macOS for iOS builds
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.27.1' # Match your fvm version
    
    - name: Get version from tag
      id: version
      run: echo "content=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Validate version consistency
      run: |
        # Get version from pubspec.yaml (remove build number)
        PUBSPEC_VERSION=$(grep "version:" guateng-wellbeing-mapper-app/pubspec.yaml | sed 's/version: //' | sed 's/+.*//' | tr -d ' ')
        
        # Get version from git tag (remove 'v' prefix)
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        
        echo "pubspec.yaml version: $PUBSPEC_VERSION"
        echo "Git tag version: $TAG_VERSION"
        
        if [ "$PUBSPEC_VERSION" = "$TAG_VERSION" ]; then
          echo "✅ Versions match!"
        else
          echo "❌ Version mismatch between pubspec.yaml ($PUBSPEC_VERSION) and git tag ($TAG_VERSION)"
          echo "Please update pubspec.yaml version to match the git tag"
          exit 1
        fi

    - name: Get flutter dependencies
      run: flutter pub get
      working-directory: guateng-wellbeing-mapper-app

    - name: Verify iOS entitlements configuration
      run: |
        echo "🔍 Verifying iOS entitlements are properly configured..."
        
        # Check entitlements file exists
        if [ ! -f "ios/Runner/Runner.entitlements" ]; then
          echo "❌ ERROR: Entitlements file missing!"
          exit 1
        fi
        
        # Check entitlements are linked in Xcode project
        if ! grep -q "CODE_SIGN_ENTITLEMENTS = Runner/Runner.entitlements" ios/Runner.xcodeproj/project.pbxproj; then
          echo "❌ ERROR: Entitlements not linked in Xcode project!"
          exit 1
        fi
        
        # Count linked configurations
        ENTITLEMENT_COUNT=$(grep -c "CODE_SIGN_ENTITLEMENTS = Runner/Runner.entitlements" ios/Runner.xcodeproj/project.pbxproj)
        if [ "$ENTITLEMENT_COUNT" -lt 3 ]; then
          echo "❌ ERROR: Entitlements not linked in all build configurations!"
          exit 1
        fi
        
        # Check location permissions in Info.plist
        REQUIRED_KEYS=("NSLocationAlwaysAndWhenInUseUsageDescription" "NSLocationAlwaysUsageDescription" "NSLocationWhenInUseUsageDescription" "NSLocationUsageDescription")
        for key in "${REQUIRED_KEYS[@]}"; do
          if ! grep -q "$key" ios/Runner/Info.plist; then
            echo "❌ ERROR: Missing location permission key: $key"
            exit 1
          fi
        done
        
        echo "✅ iOS entitlements configuration verified"
      working-directory: guateng-wellbeing-mapper-app

    - name: Statically analyze the Dart code for any errors
      run: flutter analyze
      working-directory: guateng-wellbeing-mapper-app
    
    - name: Run tests for our flutter project
      run: flutter test
      working-directory: guateng-wellbeing-mapper-app

    # Android Builds
    - name: Build Android APK (Release)
      run: flutter build apk --release --split-per-abi
      working-directory: guateng-wellbeing-mapper-app

    - name: Build Android App Bundle (Release)
      run: flutter build appbundle --release
      working-directory: guateng-wellbeing-mapper-app

    # iOS Builds
    - name: Install iOS dependencies
      run: cd ios && pod install && cd ..
      working-directory: guateng-wellbeing-mapper-app
      
    - name: Build iOS (Release)
      run: flutter build ios --release --no-codesign
      working-directory: guateng-wellbeing-mapper-app
    
    - name: Create a Release in GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          guateng-wellbeing-mapper-app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          guateng-wellbeing-mapper-app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          guateng-wellbeing-mapper-app/build/app/outputs/flutter-apk/app-x86_64-release.apk
          guateng-wellbeing-mapper-app/build/app/outputs/bundle/release/app-release.aab
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.version.outputs.content }}
        name: "Wellbeing Mapper ${{ steps.version.outputs.content }}"
        body: |
          ## Wellbeing Mapper Release ${{ steps.version.outputs.content }}
          
          ### 📱 Downloads
          - **Android App Bundle (Recommended)**: `app-release.aab` - Upload to Google Play Console
          - **Android APKs**: Individual APK files for direct installation
          - **iOS Build**: Requires archiving in Xcode for App Store Connect
          
          ### 🔧 What's Included
          - ✅ Android release builds (APK + AAB)
          - ✅ iOS release build (requires Xcode archiving for distribution)
          - ✅ Fully tested and analyzed code
          
          ### 📋 Next Steps
          1. **Android**: Upload `app-release.aab` to Google Play Console
          2. **iOS**: Archive the built app in Xcode and upload to App Store Connect
        draft: false
        prerelease: false