name: CI_tests
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    # Setup FVM and Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-3.27.1'
        
    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          gauteng-wellbeing-mapper-app/.dart_tool
          gauteng-wellbeing-mapper-app/build
          /home/runner/.pub-cache
        key: ${{ runner.os }}-flutter-deps-${{ hashFiles('gauteng-wellbeing-mapper-app/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-deps-
         
    - name: Get flutter dependencies
      run: |
        cd gauteng-wellbeing-mapper-app
        flutter pub get
    
    - name: Statically analyze the Dart code for any errors.
      run: |
        cd gauteng-wellbeing-mapper-app
        timeout 300 flutter analyze --no-fatal-infos --no-fatal-warnings || echo "Analysis completed with warnings"
    
    - name: Run tests for our flutter project.
      run: |
        cd gauteng-wellbeing-mapper-app
        flutter test --coverage --dart-define=FLUTTER_TEST_MODE=true --reporter=expanded --concurrency=6 --timeout=60s --exclude-tags=platform
      continue-on-error: false
        
    - name: Check coverage file exists
      run: |
        ls -la gauteng-wellbeing-mapper-app/coverage/ || echo "Coverage directory not found"
        
    - name: Upload coverage to codecov
      if: always()
      uses: codecov/codecov-action@v5
      with:
        file: ./gauteng-wellbeing-mapper-app/coverage/lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        verbose: false

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}